package com.claude.agent.service.review

import com.claude.agent.common.models.*

/**
 * Форматтер ревью в Markdown для публикации в PR
 * 
 * Отвечает за преобразование структурированного ревью в читаемый Markdown
 */
class ReviewMarkdownFormatter {
    
    /**
     * Форматирует ревью в Markdown для публикации в PR
     */
    fun format(review: PRReview, prInfo: PRInfo): String {
        return buildString {
            appendHeader(prInfo)
            appendSummary(review)
            appendOverallAssessment(review)
            appendDetailedComments(review)
            appendSuggestions(review)
            appendComplianceChecks(review)
            appendFooter()
        }
    }

    private fun StringBuilder.appendHeader(prInfo: PRInfo) {
        appendLine("# 🤖 AI Code Review")
        appendLine()
        appendLine("**Branch:** `${prInfo.branch}` → `${prInfo.targetBranch}`")
        appendLine()
    }

    private fun StringBuilder.appendSummary(review: PRReview) {
        appendLine("## 📝 Summary")
        appendLine(review.summary)
        appendLine()
    }

    private fun StringBuilder.appendOverallAssessment(review: PRReview) {
        appendLine("## 🎯 Overall Assessment")
        appendLine(review.overallAssessment)
        appendLine()
    }

    private fun StringBuilder.appendDetailedComments(review: PRReview) {
        if (review.comments.isEmpty()) return
        
        appendLine("## 💬 Detailed Comments")
        appendLine()
        
        val groupedComments = review.comments.groupBy { it.severity }
        
        listOf(Severity.CRITICAL, Severity.WARNING, Severity.INFO, Severity.SUGGESTION).forEach { severity ->
            val commentsForSeverity = groupedComments[severity] ?: emptyList()
            if (commentsForSeverity.isNotEmpty()) {
                appendSeveritySection(severity, commentsForSeverity)
            }
        }
    }

    private fun StringBuilder.appendSeveritySection(severity: Severity, comments: List<ReviewComment>) {
        val emoji = getSeverityEmoji(severity)
        appendLine("### $emoji ${severity.name} (${comments.size})")
        appendLine()
        
        comments.forEach { comment ->
            val location = if (comment.line != null) {
                "`${comment.file}:${comment.line}`"
            } else {
                "`${comment.file}`"
            }
            appendLine("- **$location**")
            appendLine("  ${comment.message}")
            if (comment.suggestion != null) {
                appendLine("  > 💡 Suggestion: ${comment.suggestion}")
            }
            appendLine()
        }
    }

    private fun StringBuilder.appendSuggestions(review: PRReview) {
        if (review.suggestions.isEmpty()) return
        
        appendLine("## 💡 Suggestions for Improvement")
        appendLine()
        review.suggestions.forEach { suggestion ->
            appendLine("- $suggestion")
        }
        appendLine()
    }

    private fun StringBuilder.appendComplianceChecks(review: PRReview) {
        if (review.complianceChecks.isEmpty()) return
        
        appendLine("## ✅ Compliance Checks")
        appendLine()
        review.complianceChecks.forEach { check ->
            val icon = if (check.status == "PASS") "✅" else "❌"
            appendLine("- $icon **${check.category}**: ${check.details}")
        }
        appendLine()
    }

    private fun StringBuilder.appendFooter() {
        appendLine("---")
        appendLine("*Generated by AI Code Review*")
    }

    private fun getSeverityEmoji(severity: Severity): String {
        return when (severity) {
            Severity.CRITICAL -> "🔴"
            Severity.WARNING -> "🟡"
            Severity.INFO -> "🔵"
            Severity.SUGGESTION -> "💡"
        }
    }

    /**
     * Форматирует тело inline-комментария для GitHub
     */
    fun formatInlineComment(comment: ReviewComment): String {
        return buildString {
            val severityEmoji = getSeverityEmoji(comment.severity)
            
            appendLine("$severityEmoji **${comment.severity.name}**")
            appendLine()
            appendLine(comment.message)

            if (comment.suggestion != null) {
                appendLine()
                appendLine("**Suggestion:**")
                appendLine("```")
                appendLine(comment.suggestion)
                appendLine("```")
            }
        }
    }

    /**
     * Форматирует summary для GitHub Review
     */
    fun formatReviewSummary(review: PRReview): String {
        return buildString {
            if (review.summary.isNotBlank()) {
                appendLine("## 📋 Summary")
                appendLine(review.summary)
                appendLine()
            }
            if (review.overallAssessment.isNotBlank()) {
                appendLine("## 🎯 Overall Assessment")
                appendLine(review.overallAssessment)
            }
        }
    }
}

